# Generated by Django 6.1 on 2026-08-26 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yonalish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fam', models.CharField(max_length=30)),
                ('yosh', models.PositiveBigIntegerField()),
                ('kurs', models.CharField(choices=[('1', '1-kurs'), ('2', '2-kurs'), ('3', '3-kurs'), ('4', '4-kurs')], max_length=30)),
                ('yonalish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.yonalish')),
            ],
        ),
    ]
