# Generated by Django 6.1 on 2026-08-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_student_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='yosh',
            field=models.PositiveIntegerField(),
        ),
    ]
